### PR TITLE
fix(lib/utils): simpler algorithm for removeDotSegments

### LINKED ISSUE #139: bug: fatal error for old nodes
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

-

### Plugin version

3.0.6 (latest from git)

### Node.js version

20.18.3

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

 Ubuntu 22.04.5 / Linux 6.8.0-65

### Description

I found that removeDots can take a loooot time, and cause fatal error.
I think we should rewrite this function and use more performance alg.

Stacktrace:
```console
> fasturi.equal(str,str)


#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804 (see crbug.com/1201626)
#
#
#
#FailureMessage Object: 0x7ffc8e18f600
----- Native stack trace -----

 1: 0xd41421  [node]
 2: 0x218caa1 V8_Fatal(char const*, ...) [node]
 3: 0x10d0cb8  [node]
 4: 0x12afe6f  [node]
 5: 0x12b000a  [node]
 6: 0x152a576 v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [node]
 7: 0x70bf4fed9ef6
[1]    188498 trace trap (core dumped)  node
````

### Link to code that reproduces the bug

https://gist.github.com/wooffie/8a2b461395e219dedb19ab6c7fbb945d

### Expected Behavior

No crash

### PR DESCRIPTION
**Pull request by wooffie**
Replace regex to linear algorithm. This fixes issue with fatal error/out of range. 
Closes #139 

#### Checklist

- [x] run `npm run test && npm run benchmark --if-present`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/main/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -146,35 +146,53 @@ function findToken (str, token) {
...
-    if (input.match(RDS1)) {
-      input = input.replace(RDS1, '')
-    } else if (input.match(RDS2)) {
-      input = input.replace(RDS2, '/')
-    } else if (input.match(RDS3)) {
-      input = input.replace(RDS3, '/')
-      output.pop()
+  while (input.length > 0) {
+    // Rule 2A: Remove leading "../" or "./"
+    if (input.startsWith('../')) {
```
Comment (Uzlopak) [inline lib/utils.js:156]: can we avoid startsWith?

we call startsWith with '../' and next else if is './'. Seems that we can have a combination.

File: lib/utils.js [hunk 2]
```diff
@@ -146,35 +146,53 @@ function findToken (str, token) {
...
+      input = input.slice(3)
+    } else if (input.startsWith('./')) {
+      input = input.slice(2)
+    } else if (input.startsWith('/./')) {
+      // Rule 2B: Replace "/./" or "/." with "/"
+      input = '/' + input.slice(3)
```
Comment (Uzlopak) [inline lib/utils.js:162]:
```suggestion
      input = input.slice(2)
```

File: lib/utils.js [hunk 3]
```diff
@@ -146,35 +146,53 @@ function findToken (str, token) {
...
 
-  while (input.length) {
-    if (input.match(RDS1)) {
-      input = input.replace(RDS1, '')
-    } else if (input.match(RDS2)) {
-      input = input.replace(RDS2, '/')
-    } else if (input.match(RDS3)) {
-      input = input.replace(RDS3, '/')
-      output.pop()
+  while (input.length > 0) {
```
Comment (Uzlopak) [inline lib/utils.js:154]: I guess, it could be even optimized more by counting up positions we need to slice, and at the end we make a final slice.

e.g. '../../../../../index.html' will result in 5 slice-calls. But we could collect the amount of the characters, we could throw away, and just make one slice.

Maybe we should do it in a follow up?

File: lib/utils.js (hunk 1 above)
Comment (wooffie) [reply lib/utils.js:156]: I don't wanna avoid linear startsWith to optimize check of one char

File: lib/utils.js [hunk 4]
```diff
@@ -146,35 +146,53 @@ function findToken (str, token) {
...
+    // Rule 2A: Remove leading "../" or "./"
+    if (input.startsWith('../')) {
+      input = input.slice(3)
+    } else if (input.startsWith('./')) {
+      input = input.slice(2)
+    } else if (input.startsWith('/./')) {
+      // Rule 2B: Replace "/./" or "/." with "/"
+      input = input.slice(2)
+    } else if (input === '/.') {
+      input = '/'
```
Comment (Uzlopak) [inline lib/utils.js:164]: If input = '/', then we have another iteration. We will have all checks just to do output.push(input).

So isnt it smarter to do following?

```suggestion
    } else if (input === '/.') {
      output.push('/')
      break
```

File: lib/utils.js (hunk 1 above)
Comment (wooffie) [reply lib/utils.js:156]: Yes, we can do it like this, but I don't believe that it gives really good increase. But it will make code less readble. Let someone third judge it =)

**Review by Fdawgs — CHANGES_REQUESTED** [review]
Needs a supporting unit test for the bug raised in #139

**Comment by gurgunday** [comment]
> @zekth
> 
> this pr:
> 
> ```shell
> aras@aras-HP-ZBook-15-G3:~/workspace/fast-uri$ node benchmark.js 
> fast-uri: serialize uri x 559,853 ops/sec ±1.13% (91 runs sampled)
> ```
> 
> mine:
> 
> ```shell
> aras@aras-HP-ZBook-15-G3:~/workspace/fast-uri$ node benchmark.js 
> fast-uri: serialize uri x 653,915 ops/sec ±1.55% (93 runs sampled)
> ```

@wooffie if you can confirm these results, I'd suggest applying @Uzlopak's suggestion. I understand it might look a little worse but performance is a key part of the Fastify ecosystem, and besides I'm used to seeing code like this in URI specs

Thanks again!

**Review by gurgunday — APPROVED** [review]
lgtm

**Comment by Uzlopak** [comment]
@wooffie 

Can you please add your benchmark to the suite?

Then we can make a final comparison between main and pr ;)

**Comment by Uzlopak** [comment]
@wooffie 

Well, it is more like, not that the changes resulted in a regression in other cases.

**Comment by Uzlopak** [comment]
I dont see any regression.


main:

```sh
fast-uri: parse domain x 1,118,155 ops/sec ±2.26% (90 runs sampled)
urijs: parse domain x 332,608 ops/sec ±0.70% (90 runs sampled)
WHATWG URL: parse domain x 2,862,487 ops/sec ±0.61% (94 runs sampled)
fast-uri: parse IPv4 x 1,602,475 ops/sec ±0.94% (92 runs sampled)
urijs: parse IPv4 x 287,487 ops/sec ±0.79% (94 runs sampled)
fast-uri: parse IPv6 x 860,477 ops/sec ±0.51% (94 runs sampled)
urijs: parse IPv6 x 222,171 ops/sec ±1.23% (94 runs sampled)
fast-uri: parse URN x 1,737,473 ops/sec ±0.51% (95 runs sampled)
urijs: parse URN x 859,554 ops/sec ±0.49% (93 runs sampled)
WHATWG URL: parse URN x 3,475,550 ops/sec ±0.60% (91 runs sampled)
fast-uri: parse URN uuid x 1,074,608 ops/sec ±0.99% (95 runs sampled)
urijs: parse URN uuid x 616,849 ops/sec ±0.59% (94 runs sampled)
fast-uri: serialize uri x 949,836 ops/sec ±1.49% (94 runs sampled)
urijs: serialize uri x 264,787 ops/sec ±0.47% (95 runs sampled)
fast-uri: serialize long uri with dots x 218,870 ops/sec ±0.66% (95 runs sampled)
urijs: serialize long uri with dots x 132,720 ops/sec ±0.72% (94 runs sampled)
fast-uri: serialize IPv6 x 409,919 ops/sec ±2.59% (91 runs sampled)
urijs: serialize IPv6 x 193,344 ops/sec ±0.47% (96 runs sampled)
fast-uri: serialize ws x 1,002,939 ops/sec ±0.65% (95 runs sampled)
urijs: serialize ws x 263,285 ops/sec ±0.56% (95 runs sampled)
fast-uri: resolve x 303,951 ops/sec ±0.75% (91 runs sampled)
urijs: resolve x 159,221 ops/sec ±2.24% (92 runs sampled)
```

PR:

```sh
fast-uri: parse domain x 1,120,644 ops/sec ±1.12% (90 runs sampled)
urijs: parse domain x 324,418 ops/sec ±1.68% (94 runs sampled)
WHATWG URL: parse domain x 2,781,028 ops/sec ±1.01% (93 runs sampled)
fast-uri: parse IPv4 x 1,574,421 ops/sec ±0.92% (95 runs sampled)
urijs: parse IPv4 x 270,356 ops/sec ±1.00% (93 runs sampled)
fast-uri: parse IPv6 x 829,637 ops/sec ±0.78% (93 runs sampled)
urijs: parse IPv6 x 214,412 ops/sec ±0.77% (95 runs sampled)
fast-uri: parse URN x 1,694,760 ops/sec ±0.90% (92 runs sampled)
urijs: parse URN x 844,838 ops/sec ±0.72% (97 runs sampled)
WHATWG URL: parse URN x 3,428,778 ops/sec ±0.59% (93 runs sampled)
fast-uri: parse URN uuid x 1,080,123 ops/sec ±0.62% (95 runs sampled)
urijs: parse URN uuid x 614,282 ops/sec ±0.63% (94 runs sampled)
fast-uri: serialize uri x 1,137,299 ops/sec ±0.78% (95 runs sampled)
urijs: serialize uri x 260,947 ops/sec ±0.55% (95 runs sampled)
fast-uri: serialize long uri with dots x 634,818 ops/sec ±0.69% (95 runs sampled)
urijs: serialize long uri with dots x 126,910 ops/sec ±0.63% (95 runs sampled)
fast-uri: serialize IPv6 x 427,203 ops/sec ±0.75% (96 runs sampled)
urijs: serialize IPv6 x 192,218 ops/sec ±1.24% (94 runs sampled)
fast-uri: serialize ws x 1,218,515 ops/sec ±1.29% (95 runs sampled)
urijs: serialize ws x 246,424 ops/sec ±1.12% (95 runs sampled)
fast-uri: resolve x 473,679 ops/sec ±0.92% (94 runs sampled)
urijs: resolve x 161,916 ops/sec ±0.58% (94 runs sampled)
```

**Comment by Uzlopak** [comment]
But there is one question left: Is it still everything according to the RFC? :D.

**Review by Uzlopak — APPROVED** [review]

**Review by Fdawgs — APPROVED** [review]

**Review by gurgunday — APPROVED** [review]
lgtm

**Review by zekth — APPROVED** [review]
Excellent
